## isolate_mouse_papers
Find the PMC ID of every paper that mentions mouse data.

This will then be used to identify mouse strains related to each paper by parsing the full texts on hoffman

In [2]:
# import required modules
import numpy as np
import pandas as pd

In [3]:
# import table

af = pd.read_csv('../data_tables/metadataMatrix_filtered.csv', low_memory=False)
af

,journal,pmc_ID,accession,converted_accession,repository,pmc_date,repository_date,species,hardware,library_strategy,sraAvg_length,sraBases,sraAccess,today,time_public,reuse_count,norm_reuse_count,reuse_role,pub_delay
0,eLife,PMC5630260,GSE89436,GSE89436,GEO,2017-09-27 00:00:00,2017-03-31,Mus musculus,NaN,NaN,NaN,NaN,NaN,2020-06-22,3.230137,0,0.000000,G,180.0
1,PLoS_Genet,PMC4633059,GSE62152,GSE62152,GEO,2015-11-04 00:00:00,2015-05-08,Mycobacterium tuberculosis,high-throughput sequencing,RNA-Seq,NaN,NaN,NaN,2020-06-22,5.128767,0,0.000000,G,180.0
2,Front_Microbiol,PMC5030273,SRP072068,SRP072068,SRA,2016-09-21 00:00:00,2016-03-25,insect gut metagenome,Illumina MiSeq,WGS,500.0,1.238730e+08,public,2020-06-22,4.246575,0,0.000000,G,180.0
3,Heliyon,PMC5968172,SRR6186127,SRP120276,SRA,2018-04-16 00:00:00,2017-10-18,subsurface metagenome,454 GS FLX+,AMPLICON,973.0,2.965432e+07,public,2020-06-22,2.679452,0,0.000000,G,180.0
4,ISME_J,PMC6776055,PRJNA506462,SRP170418,SRA,2019-05-30 00:00:00,2018-12-01,wastewater metagenome,Illumina HiSeq 4000,Hi-C,302.0,2.877598e+10,public,2020-06-22,1.558904,0,0.000000,G,180.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161810,Saudi_J_Biol_Sci,PMC5851940,GSM107072,GSE1456,GEO,2017-11-20,2006-05-31,Homo sapiens,in situ oligonucleotide,Expression_Array,NaN,NaN,NaN,2020-06-22,14.071233,269,19.117017,R,NaN
161811,Saudi_J_Biol_Sci,PMC5851940,GSM107231,GSE1456,GEO,2017-11-20,2006-05-31,Homo sapiens,in situ oligonucleotide,Expression_Array,NaN,NaN,NaN,2020-06-22,14.071233,269,19.117017,R,NaN
161812,Saudi_J_Biol_Sci,PMC6088103,GSE29378,GSE29378,GEO,2018-05-18,2013-06-07,Homo sapiens,oligonucleotide beads,Expression_Array,NaN,NaN,NaN,2020-06-22,7.046575,15,2.128694,R,NaN
161813,Saudi_J_Biol_Sci,PMC6088103,GSE28146,GSE28146,GEO,2018-05-18,2011-08-01,Homo sapiens,in situ oligonucleotide,Expression_Array,NaN,NaN,NaN,2020-06-22,8.898630,32,3.596059,R,NaN
161814,Saudi_Pharm_J,PMC6218847,GPL8,GSE2,GEO,2018-05-24,2001-04-26,Mus musculus,spotted DNA/cDNA,Expression_Array,NaN,NaN,NaN,2020-06-22,19.169863,13,0.678148,R,NaN

In [ ]:
# from collections import Counter
# sc = Counter(af['species'])
# specCounts = pd.DataFrame.from_dict(sc, orient = 'index').reset_index()
# specCounts.columns = ['species', 'count']
# specCounts = specCounts.sort_values(by = 'count', ascending = False)
# specCounts.head(n = 30)

In [11]:
mus = af.loc[af['species'] == "Mus musculus",:]
hom_mus = af.loc[af['species'] == "Homo sapiens;Mus musculus",:]
mice = pd.concat([mus, hom_mus])[["pmc_ID", "converted_accession", "species"]].drop_duplicates()
mice

            pmc_ID converted_accession                    species
0       PMC5630260            GSE89436               Mus musculus
30      PMC7015695           SRP144443               Mus musculus
39      PMC6901932           GSE122403               Mus musculus
41      PMC6646807           GSE121970               Mus musculus
46      PMC3060102            GSE24203               Mus musculus
...            ...                 ...                        ...
161446  PMC6713580           GSE102556  Homo sapiens;Mus musculus
161454  PMC6430658            GSE77542  Homo sapiens;Mus musculus
161463  PMC7008069            GSE76068  Homo sapiens;Mus musculus
161575  PMC6883975             GSE6135  Homo sapiens;Mus musculus
161598  PMC6819903            GSE17538  Homo sapiens;Mus musculus

[15843 rows x 3 columns]

In [10]:
#

                                                species  count
7                                          Homo sapiens  65596
0                                          Mus musculus  15944
6698                                                NaN   7320
5                                  Arabidopsis thaliana   2488
13                              Drosophila melanogaster   1985
117                           Homo sapiens;Mus musculus   1660
23                             Saccharomyces cerevisiae   1553
6780  Salmonella enterica subsp. enterica serovar Pu...   1475
35                                    Rattus norvegicus   1398
240                            Streptococcus pneumoniae   1384
186                                    Escherichia coli   1305
18                                      soil metagenome   1044
292                                   marine metagenome   1041
17                                 human gut metagenome    997
54                                           Bos taurus    952
61                                         Oryza sativa    871
92                                           Sus scrofa    852
39                                        Gallus gallus    703
175                                    human metagenome    686
12                               Caenorhabditis elegans    677
94                                          Danio rerio    654
86                                           metagenome    613
1242                             Listeria monocytogenes    601
126                               Staphylococcus aureus    514
49                                             Zea mays    510
607                                         Glycine max    470
57                     Homo sapiens;synthetic construct    459
1                            Mycobacterium tuberculosis    386
200                         Oryza sativa Japonica Group    384
121                                      gut metagenome    382